import React, { useState } from 'react';
import { StyleSheet, Text, View, TextInput, TouchableOpacity, ScrollView, SafeAreaView } from 'react-native';

export default function App() {
  const [messages, setMessages] = useState([
      { id: 1, text: "Hello! I am Personal RMI-AI. How can I assist you today?", sender: 'ai' }
        ]);
          const [inputText, setInputText] = useState('');

            const sendMessage = () => {
                if (!inputText.trim()) return;
                    
                        const newMessage = { id: Date.now(), text: inputText, sender: 'user' };
                            setMessages((prev) => [...prev, newMessage]);
                                setInputText('');

                                    // Backend Response Placeholder
                                        setTimeout(() => {
                                              setMessages((prev) => [
                                                      ...prev,
                                                              { id: Date.now() + 1, text: "Connecting to FastAPI Backend...", sender: 'ai' }
                                                                    ]);
                                                                        }, 1000);
                                                                          };

                                                                            return (
                                                                                <SafeAreaView style={styles.container}>
                                                                                      <View style={styles.header}>
                                                                                              <Text style={styles.headerText}>Personal RMI-AI</Text>
                                                                                                    </View>
                                                                                                          
                                                                                                                <ScrollView style={styles.chatContainer}>
                                                                                                                        {messages.map((msg) => (
                                                                                                                                  <View
                                                                                                                                              key={msg.id}
                                                                                                                                                          style={[
                                                                                                                                                                        styles.messageBubble,
                                                                                                                                                                                      msg.sender === 'user' ? styles.userBubble : styles.aiBubble,
                                                                                                                                                                                                  ]}
                                                                                                                                                                                                            >
                                                                                                                                                                                                                        <Text style={msg.sender === 'user' ? styles.userText : styles.aiText}>
                                                                                                                                                                                                                                      {msg.text}
                                                                                                                                                                                                                                                  </Text>
                                                                                                                                                                                                                                                            </View>
                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                          </ScrollView>

                                                                                                                                                                                                                                                                                <View style={styles.inputContainer}>
                                                                                                                                                                                                                                                                                        <TextInput
                                                                                                                                                                                                                                                                                                  style={styles.input}
                                                                                                                                                                                                                                                                                                            placeholder="Type a message..."
                                                                                                                                                                                                                                                                                                                      value={inputText}
                                                                                                                                                                                                                                                                                                                                onChangeText={setInputText}
                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                <TouchableOpacity style={styles.sendButton} onPress={sendMessage}>
                                                                                                                                                                                                                                                                                                                                                          <Text style={styles.sendButtonText}>Send</Text>
                                                                                                                                                                                                                                                                                                                                                                  </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                        </View>
                                                                                                                                                                                                                                                                                                                                                                            </SafeAreaView>
                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                              const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                container: { flex: 1, backgroundColor: '#f5f5f5' },
                                                                                                                                                                                                                                                                                                                                                                                  header: { padding: 16, backgroundColor: '#4F46E5', alignItems: 'center', marginTop: 30 },
                                                                                                                                                                                                                                                                                                                                                                                    headerText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
                                                                                                                                                                                                                                                                                                                                                                                      chatContainer: { flex: 1, padding: 16 },
                                                                                                                                                                                                                                                                                                                                                                                        messageBubble: { padding: 12, borderRadius: 12, marginBottom: 10, maxWidth: '80%' },
                                                                                                                                                                                                                                                                                                                                                                                          userBubble: { backgroundColor: '#4F46E5', alignSelf: 'flex-end' },
                                                                                                                                                                                                                                                                                                                                                                                            aiBubble: { backgroundColor: '#e5e7eb', alignSelf: 'flex-start' },
                                                                                                                                                                                                                                                                                                                                                                                              userText: { color: '#fff' },
                                                                                                                                                                                                                                                                                                                                                                                                aiText: { color: '#000' },
                                                                                                                                                                                                                                                                                                                                                                                                  inputContainer: { flexDirection: 'row', padding: 12, backgroundColor: '#fff' },
                                                                                                                                                                                                                                                                                                                                                                                                    input: { flex: 1, borderWidth: 1, borderColor: '#ccc', borderRadius: 8, paddingHorizontal: 12, height: 40 },
                                                                                                                                                                                                                                                                                                                                                                                                      sendButton: { marginLeft: 8, backgroundColor: '#4F46E5', justifyContent: 'center', paddingHorizontal: 16, borderRadius: 8 },
                                                                                                                                                                                                                                                                                                                                                                                                        sendButtonText: { color: '#fff', fontWeight: 'bold' }
                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                       






